"use client";
import "./globals.css";
import { Roboto } from "next/font/google";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { auth } from "../firebase";
import { useRouter } from "next/navigation";
import { onAuthStateChanged } from "firebase/auth";
import { UserContext, User } from "@/contexts/UserContext";
import { useEffect, useState } from "react";

const theme = createTheme({
  palette: {
    primary: {
      main: "#274D76",
    },
  },
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "EventTix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [userData, setUserData] = useState<User | null>(null);
  const router = useRouter();

  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        setUserData({ uid: user.uid, email: user.email as string });
      } else {
        router.push("/login");
      }
    });
  }, [router]);

  return (
    <ThemeProvider theme={theme}>
      <UserContext.Provider value={userData}>
        <html lang="en">
          <body className={roboto.className}>{children}</body>
        </html>
      </UserContext.Provider>
    </ThemeProvider>
  );
}
